/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'FOC_PointModel' 
 * Target:  'OFC_PointModel' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "LKS32MC07x.h"



#endif /* RTE_COMPONENTS_H */
